name: coffee_shop
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.5.0
  shared_preferences: ^2.5.5
  intl: any
  lottie: ^3.5.1
  flutter_riverpod: ^3.4.2
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true

  uses-material-design: true
